=== wheelerkeith/cs213/public_html/week08/BSA.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT bsa (council+)>
<!ELEMENT council (name, troop+)>
<!ELEMENT troop (number, name, scout+)>
<!ELEMENT scout (firstName, lastName, address, phone, rank+, meritBadge+)>
<!ELEMENT rank (name, date-earned)>
<!ELEMENT meritBadge (name, date-earned)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT date-earned (#PCDATA)>

=== wheelerkeith/cs213/public_html/week08/BSA.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bsa SYSTEM "BSA.dtd">
<bsa>
	<council>
		<name>Council Name</name>
		<troop>
			<number>Troop Number</number>
			<name>Troop Name</name>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
		</troop>
		<troop>
			<number>Troop Number</number>
			<name>Troop Name</name>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
		</troop>
	</council>
	<council>
		<name>Council Name</name>
		<troop>
			<number>Troop Number</number>
			<name>Troop Name</name>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
		</troop>
		<troop>
			<number>Troop Number</number>
			<name>Troop Name</name>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
			<scout>
				<firstName>Scout First Name</firstName>
				<lastName>Scout Last Name</lastName>
				<address>Address</address>
				<phone>Phone</phone>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<rank>
					<name>Rank</name>
					<date-earned>Date Earned</date-earned>
				</rank>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
				<meritBadge>
					<name>Badge</name>
					<date-earned>Date Earned</date-earned>
				</meritBadge>
			</scout>
		</troop>
	</council>
</bsa>
